FROM debian:trixie
RUN apt-get update && apt-get -y install build-essential libffi-dev docker.io git
RUN git clone https://github.com/ashinn/chibi-scheme.git --depth=1
RUN cd chibi-scheme && make && make install
RUN snow-chibi install --impls=chibi --always-yes test-r7rs
